// app/project/page.tsx
"use client";
import React, { useState } from 'react';
import Image from 'next/image';
import project1Img from '@/assets/cisco.png';
import project2Img from '@/assets/gsf.png';
import project2ImgLogo from '@/assets/gsf_logo.png';
import project3Img from '@/assets/rhul.png';
import project3ImgLogo from '@/assets/rhul_logo.png';
import projectNoteImg from '@/assets/note.png';
import projectNoteImgLogo from '@/assets/note_logo.png';
import projectNextImage from '@/assets/nextjs.png';

const projects = [
    {
        id: 1,
        title: "Cisco Internship",
        date: "May 2024 - Sep 2024",
        logo: project1Img,
        thumbnail: project1Img,
        technologies: [ "C++", "Python", "Network", "Queueing Theories" ],
        description: "Extend the existing Network Testing Pipe using C++ and Python",
        fullContent: `
         Our team expand on the existing Network Testing Pipe for Cisco's WebEx, a popular video-conferencing software.
         Throughout the project, we worked closely with the Cisco WebEx and Meraki teams to implement the new functionalities.
         This empowered us with first-hand experience working in an enterprise development environment playing a part in
        a large-scale project and working with legacy code.`
    },
    {
        id: 2,
        title: "Green Software Foundation Internship",
        date: "Jan 2024 - Mar 2024",
        logo: project2ImgLogo,
        thumbnail: project2Img,
        technologies: [ "TypeScript", "Python", "Optimisation Algorithm" ],
        description: "Develope new plugins/models for Green Software Foundation using TypesScript and Python",
        fullContent: `Developed new plugins/models for the project IF(Impact Engine Framework) using TypeScript.
        The plugins successfully detected and reduced carbon footprints generated by cloud servers.
        This is achieved by using the backpack algorithm while other members develop further with more functionalities.`
    },
    {
        id: 3,
        title: "Reasearch Assistant at Royal Holloway",
        date: "June 2022 - July 2022",
        logo: project3ImgLogo,
        thumbnail: project3Img,
        technologies: [ "Data Analysis", "Quantitative Research" ],
        description: "Assisting the research of Dr Beatrice of RHUL",
        fullContent: `Conducting quantitative research and assit in data analysis for Dr Beatrice's research on the impact
                    of emojis and other interactions on the online learning of the students.`
    },
    {
        id: 4,
        title: "Essential Note",
        date: "Ongoing",
        logo: projectNoteImgLogo,
        thumbnail: projectNoteImgLogo,
        technologies: [ "Electron", "React", "TypeScript", "React Native" ],
        description: "A cross-platform minimalist note-taking app.",
        fullContent: `I built a simple App with cloud sync and basic funtionalities using Electron and React with TypeScript.
         I am currently extending the cross-platform functionalities to mobile devices for both Android and IOS using React
          Native to achieve true cross-platform experience. The goal is to eliminate all unnecessary features and provide a clean and pratical 
          experiences for users to record their ideas and daily activities.`
    },
    {
        id: 5,
        title: "Wed Development",
        date: "Ongoing",
        logo: projectNextImage,
        thumbnail: projectNextImage,
        technologies: [ "React", "JavaScript", "TypeScript", "Tailwind CSS" ],
        description: "Building my personal website to showcase my projects and skills.",
        fullContent: `Build the first website using JavaScript, React with Vite and deployed on Firebase. The second website uses NEXT.js
                      with TypeScript and also Tailwind CSS. The first website initially used multiple APIs with backend built on Java SpringBoot
                      but it was later removed due to Google Cloud's surge in cloud charges.`
    }
];

export default function Project()
{
    const [ selectedProject, setSelectedProject ] = useState( projects[ 0 ] );

    return (
        <div className="bg-white dark:bg-black min-h-screen p-4 sm:p-8 font-[family-name:var(--font-geist-sans)]">
            {/* Main content with two columns */}
            <div className="flex flex-col lg:flex-row mt-8 gap-[200px]">
                {/* Left main content - Project details */}
                <div className="w-full lg:w-3/5">
                    <div>
                        {/* 更改高度比例和添加最大高度限制 */}
                        <div className="relative h-[400px] lg:h-[600px] max-h-[600px] rounded-xl overflow-hidden">
                            <Image
                                src={selectedProject.thumbnail}
                                alt={selectedProject.title}
                                fill
                                style={{ objectFit: "contain" }}
                                className="rounded-t-xl"
                            />

                            <div className="absolute inset-0 flex items-center justify-center">
                            </div>
                        </div>

                        {/* Project details - 增加内容区比例 */}
                        <div className="p-20 sm:p-8 lg:p-20  rounded-b-xl shadow-sm">
                            {/* 标题区域 - 添加横向排列的标题和日期 */}
                            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-6 border-b border-gray-100 dark:border-gray-700 pb-4">
                                <h1 className="text-2xl sm:text-3xl me:text-4xl lg:text-6xl font-bold font-[family-name:var(--font-geist-mono)] text-gray-900 dark:text-white tracking-tight">
                                    {selectedProject.title}
                                </h1>
                                <div className="mt-2 sm:mt-0">
                                    <span className="bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 text-sm font-medium rounded-full px-3 py-1 flex items-center space-x-1">
                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                        </svg>
                                        <span>{selectedProject.date}</span>
                                    </span>
                                </div>
                            </div>

                            {/* 技术标签 - 新增内容 */}
                            {selectedProject.technologies && (
                                <div className="flex flex-wrap gap-2 mb-6">
                                    {selectedProject.technologies.map( ( tech, index ) => (
                                        <span key={index} className="bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-xs font-medium rounded-md px-2.5 py-1 flex items-center">
                                            {tech}
                                        </span>
                                    ) )}
                                </div>
                            )}

                            {/* 简介 - 使用更醒目的样式 */}
                            <div className="mb-8">
                                <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-3">Project Overview</h2>
                                <p className="text-gray-700 dark:text-gray-300 leading-relaxed border-l-4 border-blue-500 dark:border-blue-400 pl-4 py-1 italic">
                                    {selectedProject.description}
                                </p>
                            </div>

                            {/* 详细内容 - 提升可读性 */}
                            <div className="prose dark:prose-invert prose-blue prose-headings:font-medium prose-headings:tracking-tight prose-a:text-blue-600 dark:prose-a:text-blue-400 max-w-none">
                                <div className="space-y-4">
                                    {selectedProject.fullContent}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right sidebar - Project navigation */}
                <div className="w-full lg:w-1/4 mt-8 lg:mt-0">
                    <div className="space-y-4">
                        {projects.map( ( project ) => (
                            <div
                                key={project.id}
                                className={`
                                    flex items-center p-4 rounded-lg cursor-pointer 
                                    hover:bg-gray-100 dark:hover:bg-gray-700 
                                    ${selectedProject.id === project.id ? 'bg-gray-100 dark:bg-gray-700 ring-2 ring-blue-500' : ''}
                                `}
                                onClick={() => setSelectedProject( project )}
                            >
                                <div className="w-16 h-16 relative rounded-lg overflow-hidden flex-shrink-0">
                                    <Image
                                        src={project.logo}
                                        alt={project.title}
                                        fill
                                        style={{ objectFit: "cover" }}
                                    />
                                </div>

                                <div className="ml-4 flex-grow">
                                    <h3 className="font-bold text-lg text-gray-900 dark:text-white">
                                        {project.title}
                                    </h3>
                                    <div className="text-gray-500 dark:text-gray-400">
                                        {project.date}
                                    </div>
                                </div>
                            </div>
                        ) )}
                    </div>
                </div>
            </div>
        </div>
    );
}